#! /bin/sh

# Restore wallpaper
nitrogen --restore

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         4
bspc config window_gap           5
bspc config split_ratio          0.50

bspc config focused_border_color "#6272a4"
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name Vimix-white-cursors

# workspace 1 (Terminals)
declare -a terminal=(Alacritty Xfce4-terminal)
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst 

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
lx session

# Launch keybindings daemon
sxhkd &

# start compositor
picom --config $HOME/.config/bspwm/picom.conf &

